=== Obey the general contract when overriding equals

==== 主旨

* overriding equals方法與重點

==== 說明

* overriding equals看起來很簡單，但如果方法錯誤，可能會造成更嚴重的後果

* 避免問題最簡單的方法是不重寫equals，在這種情況下，類別的每個物件就是只能與自己相等

* 如果有以下情況，則overriding equal是正確的行為:

** 該類別的每個實作在本質上是唯一的 +
如像Thread這樣代表活動的實體物件，而不是數值的物件

** 該類別不需要提供"邏輯等式" +
例如，java.util.regex.Pattern可以overriding equals，來檢查兩個Pattern物件是否使用完全相同的正則表達式(regex)，而設計者認為不需要或不想要使用這個功能

** 一個覆類別已經overriding equals，則此行為對這個類別來說是合適的 +
例如，大部分的Set從AbstractSet、List從AbstractList、Map從AbstractMap繼承equals

** 這個類別是私有的，而且肯定equals方法永遠不會被呼叫 +
如果你對風險非常敏感，你可以overriding equals確保他不會被呼叫 +

* 當一個類別判別是否相等的概念與基本類型不同時並且，父類別沒有覆寫equals時，此時覆寫equals是合適的。

* 程式設計師，希望找出兩個物件的內容邏輯是否相同，且不是比較引用的參照。

[source,java]
----
@Override
public boolean equals(Object o){
    throw new AssertionError();
}
----

* 一種不需要overriding equals的類別，是使用static factory控制的類別，以確保該類別最多只存在一個物件，列舉就類似這種類型

* 當你要overrideing equals時，必須遵守相關規範，以下是Object的規範:

** 對於equals方法實現等價關係的屬性:

*** Reflexive: 對於任何非NULL的參照引用x，x.equals(x)必須返回true。

*** Symmetric: 對於任何非NULL的參照引用x、y，x.equals(y)必須返回true，y.equals(x)必須返回true

*** Transitive: 對於任何非NULL的參照引用x、y、z，如果x.equals(y)為true，且y.equals(z)為true，那麼x.equals(z)也必須為返回true

*** Consistent: 對於任何非NULL的參照引用x、y, 多次呼叫x.equals(y)的返回值必須一致，只要在等值比較中的數據沒有被修改

*** 對於任何非NULL的參照引用X，則x.equals(null)必須返回false

* 以上規則如果違反了，可能會發現你的程式行為不正常或崩潰，且要找出原因非常困難

詳細說明:

* Reflexive: 如果違反此規則，則可能造成同一個物件可多次加入集合當中。

* Symmetric: +
參考下面的這個類別，他實作了一個部區分大小寫的字串，該字串會不分大小寫的做比較。

[source,java]
----
public final class CaseInsensitiveString {
    private final String s;

    public CaseInsensitiveString(String s) {
        this.s = Objects.requireNonNull(s);
    }


    @Override
    public boolean equals(Object o) {
        if (o instanceof CaseInsensitiveString) {
            return s.equalsIgnoreCase(((CaseInsensitiveString) o).s);
        };
        if (o instanceof String) {
            return s.equalsIgnoreCase((String) o);
        };
        return false;
    }

}
----

此時因為在equals內有可以比較String的部分，所以我們利用此方法來做比較。

[source,java]
----
CaseInsensitiveString cis = new CaseInsensitiveString("Polish");
String s = "polish";

cis.equals(s);
s.equals(cis);
----

在此方法中，cis.equals(s)的返回值會等於true，但在s.equals(cis)的返回值會是false，此部分就違反了對稱性規則，且將CaseInsensitiveString放入到一個集合當中。

[source,java]
----
CaseInsensitiveString cis = new CaseInsensitiveString("Polish");
String s = "polish";
List<CaseInsensitiveString> list = new ArrayList<>();
list.add(cis);
----

此時list.contains(s)會返回什麼呢? +
以目前openjdk的實作中，他會返回false，但在另外的jdk可能會返回true或拋出異常，一旦違反等價規範，你很分辨物件在與其他物件的判別中，將如何處理

想要消除這個問題，只需要從equals方法中刪除試圖與String互相操作的錯誤想法。

[source,java]
----
public final class CaseInsensitiveString {
    private final String s;

    public CaseInsensitiveString(String s) {
        this.s = Objects.requireNonNull(s);
    }


    @Override
    public boolean equals(Object o) {
        return o instanceof CaseInsensitiveString &&((CaseInsensitiveString) o).s.equalsIgnoreCase(s);
    }

}
----

* Transitive : +

[source,java]
----
public class Point {
    private final int x;
    private final int y;

    public Point(int x, int y) {
        this.x = x;
        this.y = y;
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Point)) {
            return false;
        }
        Point p = (Point) o;
        return p.x == x && p.y == y;
    }
}
----

當你想繼承此類別，增加顏色屬性:

[source,java]
----
public class ColorPoint extends Point {
    private final Color color;

    public ColorPoint(int x, int y, Color color) {
        super(x, y);
        this.color = color;
    }
}
----

該怎麼看equals方法呢? +
如果你完全不考慮，那麼equals就是會從Point繼承的，那麼顏色屬性在此就會被忽略。，但顯然這是不能接受的，所以將複寫equals當，方法參數中，其物件變數color

[source,java]
----
@Override
public boolean equals(Object o) {
    if (!(o instanceof ColorPoint)){
        return false;
    }
    return super.equals(o) && ((ColorPoint) o).color == color;
}
----

==== 總結